#!/bin/bash

export PIPENV_VENV_IN_PROJECT=1
export PIPENV_IGNORE_VIRTUALENVS=1
export PIPENV_NO_INHERIT=1
export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.ustc.edu.cn/homebrew-bottles
export BAT_THEME="OneHalfDark"
export PATH="${PATH}:$HOME/.local/bin"
export GOPROXY=https://goproxy.cn
export SERVERLESS_PLATFORM_VENDOR=aws

# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi
